version: "3.7"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - node-app
        networks:
            - laravel

    node-app:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www/
        volumes:
            - ./:/var/www

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "7001:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # db mysql
    db:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
            MYSQL_USER: ${DB_USERNAME:-username}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3208:3306"
        networks:
            - laravel

    # redis
    redis:
        image: redis:latest
        networks:
            - laravel

    mailhog:
        image: mailhog/mailhog
        networks:
            - laravel
        ports:
            - "1128:1025"
            - "8128:8025"

networks:
    laravel:
        driver: bridge
